2025-04-13 23:14:54,085 [INFO] Starting homing procedure
2025-04-13 23:15:09,526 [INFO] Homing procedure complete and speed limits set
2025-04-13 23:15:09,529 [INFO] Homing complete
2025-04-13 23:15:44,862 [ERROR] Error in status_broadcast_loop
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 563, in _read
    return self._state_to_value(self.pin.state)
                                ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 584, in _check_open
    super()._check_open()
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 213, in _check_open
    raise DeviceClosed(
gpiozero.exc.DeviceClosed: OutputDevice is closed or uninitialized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/berke/Desktop/PurrfectSpray/Code/app.py", line 185, in status_broadcast_loop
    'laser': laser_pin.value,
             ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gpiozero/output_devices.py", line 121, in value
    return super().value
           ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 602, in value
    return self._read()
           ^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 565, in _read
    self._check_open()
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 587, in _check_open
    raise GPIODeviceClosed(str(e))
gpiozero.exc.GPIODeviceClosed: OutputDevice is closed or uninitialized
